######################################################################
# Automatically generated by qmake (3.0) ?? ?? 21 15:02:28 2020
######################################################################

TEMPLATE = app
TARGET = testqtGUI_two
INCLUDEPATH += .

# Input
HEADERS += testqtgui.h ui_testqtgui.h
FORMS += testqtgui.ui
SOURCES += main.cpp qrc_testqtgui.cpp testqtgui.cpp
RESOURCES += testqtgui.qrc
